language: java
install: true

script: mvn clean package -DskipTests=true
before_install:
    - sudo apt-get update
    - sudo apt-get install groovy

jdk:
  - oraclejdk9
notifications:
  email: false
